services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge